### PR TITLE
feat: SwapDetails screen

### PR DESCRIPTION
**Pull request by lrupnikk**

### CODE REVIEW

**Comment by dabitdev** [comment]
hi @lrupnikk, could you port your swap details on the existing empty fragment `SwapDetailsFragment`?
Or in other words, remove the empty fragment and add yours in the navigation graph.

**Comment by lrupnikk** [comment]
So I'll just  merge my PR into yours and solve all the conflicts. That should do.

**Comment by dabitdev** [comment]
💡 my changes are already merged in `mit-android`

**Comment by lrupnikk** [comment]
Uh sorry mb. Then'll just solve the conflicts.

**Review by roknovak — APPROVED** [review]

**Review by dabitdev — APPROVED** [review]
LGTM

**Pull request merged**
